input.onButtonPressed(Button.A, function () {
    music.playTone(392, music.beat(BeatFraction.Double))
    basic.pause(20)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(294, music.beat(BeatFraction.Double))
    basic.pause(20)
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(311, music.beat(BeatFraction.Double))
    basic.pause(20)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(294, music.beat(BeatFraction.Double))
    basic.pause(20)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(233, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(220, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(233, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(196, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(185, music.beat(BeatFraction.Double))
    basic.pause(20)
    music.playTone(185, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(294, music.beat(BeatFraction.Double))
})
input.onButtonPressed(Button.B, function () {
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(466, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(440, music.beat(BeatFraction.Double))
    basic.pause(20)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(311, music.beat(BeatFraction.Whole))
    basic.pause(20)
    music.playTone(311, music.beat(BeatFraction.Whole))
})
basic.forever(function () {
	
})
